# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DreamMeeting' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DreamMeeting
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'GoogleAppMeasurement'
  pod 'Kingfisher', '~> 5.0'
  pod 'JGProgressHUD', '~> 2.0.3'

end
